package com.easydora.orders.statemachine;

public enum OrderEvent {
    PAYMENT_RECEIVED, //PAGAMENTO_RECEBIDO
    PAYMENT_FAILED, //FALHA_NO_PAGAMENTO
    START_PROCESSING, //INICIAR_PROCESSAMENTO
    INVENTORY_RESERVED, //ESTOQUE_RESERVADO
    INVENTORY_FAILED, //FALHA_NO_ESTOQUE
    SHIP_ORDER, //ENVIAR_PEDIDO
    DELIVER_ORDER, //ENTREGAR_PEDIDO
    CANCEL_ORDER, //CANCELAR_PEDIDO
    INITIATE_REFUND, //REEMBOLSAR_PEDIDO
    REFUND_COMPLETED, //REEMBOLSO_CONCLUIDO
    REFUND_FAILED, //FALHA_NO_REEMBOLSO (ADR-0034)
    RETRY_REFUND //REEMBOLSO_TENTAR_NOVAMENTE (ADR-0034's remediation tooling)
}