package com.easydora.orders.statemachine;

public enum OrderEvent {
    PAYMENT_RECEIVED, //PAGAMENTO_RECEBIDO
    PAYMENT_FAILED, //FALHA_NO_PAGAMENTO
    INVENTORY_RESERVED, //ESTOQUE_RESERVADO
    INVENTORY_FAILED, //FALHA_NO_ESTOQUE
    SHIP_ORDER, //ENVIAR_PEDIDO
    DELIVER_ORDER, //ENTREGAR_PEDIDO
    CANCEL_ORDER, //CANCELAR_PEDIDO
    INITIATE_REFUND, //REEMBOLSAR_PEDIDO
}