# Configuração do servidor
server.port=8081
spring.application.name=auth-service

# Profile ativo (default para produção/docker)
spring.profiles.active=prod

# Configurações comuns
spring.jpa.properties.hibernate.default_schema=auth_schema
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret
jwt.secret=${JWT_SECRET:default-secret-key}

spring.profiles.active=dev