server.port=8085
spring.application.name=billing-service

# Profile ativo (default para desenvolvimento)
spring.profiles.active=dev

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=billing_schema

spring.rabbitmq.connection-timeout=5s
rabbitmq.queue.order-created=billing.order.created.queue
