spring.application.name=billing-service

spring.datasource.url=jdbc:postgresql://localhost:5432/easydora
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD:local_dev_placeholder}

#DEV
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=billing_schema
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# For dev - repair checksums
spring.flyway.repair.enabled=true
spring.flyway.clean-on-validation-error=true
spring.flyway.repair-on-migrate=true
spring.flyway.validate-on-migrate=false


server.port=8085

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=${RABBITMQ_PASSWORD:local_dev_placeholder}
spring.rabbitmq.connection-timeout=5s
rabbitmq.queue.order-created=billing.order.created.queue
