# ============================================
# DATABASE CONFIGURATION - DEVELOPMENT
# ============================================

# PostgreSQL Development
spring.datasource.url=jdbc:postgresql://localhost:5432/easydora
spring.datasource.username=admin
spring.datasource.password=69Nxa3dfk2M%40

# JPA Development Settings

#spring.jpa.hibernate.ddl-auto=validate
#DEV
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=products_schema

# ============================================
# MESSAGE BROKER CONFIGURATION - DEVELOPMENT
# ============================================

# RabbitMQ Development
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=87j9d]#2@5B5

# ============================================
# LOGGING CONFIGURATION - DEVELOPMENT
# ============================================

# Logging Levels for Development
logging.level.com.easydora.products=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction=DEBUG

# ============================================
# APPLICATION SPECIFIC - DEVELOPMENT
# ============================================

# Habilita endpoints de debug
management.endpoints.web.exposure.include=health,info,metrics,beans
management.endpoint.health.show-details=always

# ============================================
# FLYWAY CONFIGURATION - DEVELOPMENT
# ============================================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=products_schema
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true